### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-wq6yx#2]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by sauravpanchal** [comment]
- Handling broken images by changing image's source path on error

![image](https://user-images.githubusercontent.com/61927693/184468331-ea93ddca-a773-4790-8a80-0d2ebe917605.png)

- When user uploads item without image, instead of broken image `placeholder.png` image will be displayed as default

![image](https://user-images.githubusercontent.com/61927693/184468271-cc059389-9fe2-47c8-b241-3f87ec194e72.png)

**Comment by sauravpanchal** [comment]
Merged PR #5
